version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: lifebutler
      POSTGRES_PASSWORD: rPwAXOtmKLamZpX5TaQu6H62k5oIPJ
    volumes:
      - lifebutler_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass pSkRMj-wIQOpQ-3NOxQPBYyE6uzDphxa

  server:
    build:
      context: .
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: lifebutler
      DATABASE_USER: postgres
      DATABASE_PASSWORD: rPwAXOtmKLamZpX5TaQu6H62k5oIPJ
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pSkRMj-wIQOpQ-3NOxQPBYyE6uzDphxa
    command:
      - dart
      - bin/main.dart
      - --apply-migrations

volumes:
  lifebutler_data:
