# Passwords used across all configurations
shared:
  mySharedPassword: my password

# Development environment (LOCAL)
development:
  database: 'rPwAXOtmKLamZpX5TaQu6H62k5oIPJ'
  redis: pSkRMj-wIQOpQ-3NOxQPBYyE6uzDphxa
  serviceSecret: A8XucdFopGq6UMCRZRdrXmRenTaHL9ow
  emailSecretHashPepper: GnFVDo4GvV8ck_CRJ_VrkJMbWxF_BLDb
  jwtHmacSha512PrivateKey: JbgZ9UOGr2fvy6d2QyYcB-8ua7Ivpd9z
  jwtRefreshTokenHashPepper: mQnm2S9Woz8iWKgXKZNtLObVjYmnl9LN

# Test environment
test:
  database: 'rPwAXOtmKLamZpX5TaQu6H62k5oIPJ'
  redis: 5388gBMZLoGTDa1DNZG5hCC4GRRTskbV
  emailSecretHashPepper: YLeVSlNcs1-LnvEP7snQJKDNDg-8GNz7
  jwtHmacSha512PrivateKey: b-V9ovifq0cIudOXFAFVVuQBApbwtdVd
  jwtRefreshTokenHashPepper: NcFL5Z0YZ0vC3iVVMxWxbEgGK32AdT8F

# Staging environment
staging:
  database: 'rPwAXOtmKLamZpX5TaQu6H62k5oIPJ'
  serviceSecret: I8JjBgh12uJh84JqKB2xvkRm2C39rEwO
  emailSecretHashPepper: _fsfFeySqvmhed0etlG0s0cfsWxiqlpJ
  jwtHmacSha512PrivateKey: nb6MQehF38BMVs-QYitxWgRBKn6o1xl2
  jwtRefreshTokenHashPepper: J3F8hCkub2xruAQiaHNopvezA8a4P6kP

# Production environment
production:
  database: 'rPwAXOtmKLamZpX5TaQu6H62k5oIPJ'
  serviceSecret: PA9q9lqFD-gXMN3fXNh9nE_2XYhsK92u
  emailSecretHashPepper: oFdxFvzKv9R2IHuoopo1mIrLs4PggGKk
  jwtHmacSha512PrivateKey: l_w7IDjKUgTI5vGZtb59M1y5ANLVZ03o
  jwtRefreshTokenHashPepper: MM27STJE1ViY0cftG2Rguf2T9R5qt0t8
